### ISSUE TITLE
Not sure why but it makes the game crash

### ISSUE THREAD

**Issue by x2hunter** [Nitrrine/WildfireFemaleGenderMod_Reloaded#4]
the original mod works but this one crashes when I load my world not sure why maybe its some other mods conflicting?

**Comment by x2hunter** [comment]
ahhh nvm im dumb Its an issue on my end

**Comment by MinekPo1** [comment]
My sibling in Cthulhu, please add details when you solve your own issues if any unfortunate soul has the same problem as you.
