### ISSUE TITLE
no hurt sounds in multiplayer

### ISSUE THREAD

**Issue by SabaJepeto69** [Nitrrine/WildfireFemaleGenderMod_Reloaded#6]
there are no hurt sounds in multiplayer servers
:(

**Comment by SabaJepeto69** [comment]
> Hello!
> 
> Please upload the game log to https://mclo.gs/ and send it here

how do i get logs?

**Comment by Nitrrine** [comment]
> 
> how do i get logs?
> 

In the Minecraft root folder, it's located in %appdata%/.minecraft/logs

Upload latest.log to mclo.gs and send link here

**Comment by SabaJepeto69** [comment]
> > how do i get logs?
> 
> In the Minecraft root folder, it's located in %appdata%/.minecraft/logs
> 
> Upload latest.log to mclo.gs and send link here

https://mclo.gs/TH0vSjZ

**Comment by Nitrrine** [comment]
I'll try to fix that in the nearest time
